parameters:
#    dv_enrich.example.class: DV\Bundle\EnrichBundle\Example

services:
#    dv_enrich.example:
#        class: %dv_enrich.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
